version: '3.5'
services:
    postgres:
        image: postgres:11.4-alpine
        container_name: postgres
        hostname: postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: lethu
            POSTGRES_PASSWORD: lethu
            POSTGRES_DB: instacom
        # volumes:
        #   - ./init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
